-- Intentionally empty in deploy migrations.
--
-- The original file contained a transaction-only smoke test that attempted to
-- SET ROLE supabase_admin. Supabase's migration runner does not permit that
-- role switch, so the test belongs in an explicit Management API test job, not
-- in the production migration chain.
